### ISSUE TITLE
feat: add loading from multiple configs directories

### ISSUE THREAD

**Issue by saemanas** [bybatkhuu/mod.python-config#4]
<img width="194" alt="Screenshot 2023-06-19 오후 6 42 48" src="https://github.com/bybatkhuu/mod.python-config/assets/68885314/f18ce939-6731-4d83-b909-57ee159841e1">

**Comment by bybatkhuu** [comment]
Docs:     <https://github.com/bybatkhuu/mod.python-config/tree/main/docs>
Examples: <https://github.com/bybatkhuu/mod.python-config/tree/main/examples/advanced>

Commit ID: [**`9047904`**](https://github.com/bybatkhuu/mod.python-config/commit/9047904e68b8e0797c610238d8e44fb4a38b2356)
